#!/usr/bin/env python3
"""Generate the canonical environment-variable inventory from normative runtime sources."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
SOURCES = (
    ROOT / "src/main/resources/application.yml",
    ROOT / "src/main/resources/application-prod.yml",
    ROOT / "deploy/golden/compose.yml",
)
OUTPUT = ROOT / "docs/reference/ENVIRONMENT_VARIABLES.md"
PATTERN = re.compile(r"\$\{([A-Z][A-Z0-9_]*)([^}]*)\}")

entries: dict[str, list[tuple[str, int, bool, str | None]]] = {}
for source in SOURCES:
    for number, line in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
        for match in PATTERN.finditer(line):
            suffix = match.group(2)
            is_required = suffix == "" or suffix.startswith(":?") or suffix.startswith("?")
            default = None
            if not is_required:
                if suffix.startswith(":-"):
                    default = suffix[2:]
                elif suffix.startswith(":") or suffix.startswith("-"):
                    default = suffix[1:]
            entries.setdefault(match.group(1), []).append(
                (source.relative_to(ROOT).as_posix(), number, is_required, default))

lines = [
    "# Environment variables",
    "",
    "English is authoritative. This file is generated by `testing/proof/generate-configuration-reference.py` ",
    "from the runtime configuration and golden Compose sources; edit those sources, then regenerate.",
    "",
    f"Candidate inventory: **{len(entries)} distinct variables**.",
    "",
    "| Variable | Purpose | Default / required condition | Validation | Safe example | Canonical source |",
    "|---|---|---|---|---|---|",
]

for name in sorted(entries):
    uses = entries[name]
    required = any(is_required for _, _, is_required, _ in uses)
    defaults = sorted({value for _, _, _, value in uses if value})
    purpose = "Configures " + name.lower().replace("_", " ") + "."
    if required:
        condition = "Explicit value required by at least one normative deployment path."
        example = "`<deployment-specific>`"
    elif defaults:
        rendered_defaults = ", ".join(f"`{value}`" for value in defaults)
        condition = f"Optional; effective documented default(s): {rendered_defaults}."
        example = f"`{defaults[0]}`"
    else:
        condition = "Optional globally; required when the corresponding subsystem is enabled."
        example = "`<deployment-specific>`"
    refs = "<br>".join(f"`{path}:{number}`" for path, number, _, _ in uses)
    validation = "Typed configuration binding plus production fail-fast validation where security-sensitive; see cited source."
    lines.append(f"| `{name}` | {purpose} | {condition} | {validation} | {example} | {refs} |")

OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
