package io.github.brenomega.authkit.infrastructure.audit;

/**
 * Durable security event names used for incident response and compliance review.
 */
public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_RESET_FAILED,
    REFRESH_TOKEN_ROTATED,
    REFRESH_TOKEN_REUSE_DETECTED,
    REFRESH_TOKEN_FAILED,
    LOGOUT,
    LOGOUT_ALL,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED,
    MFA_CHANGED,
    MFA_CHALLENGE_ISSUED,
    MFA_CHALLENGE_VERIFIED,
    MFA_CHALLENGE_FAILED,
    MFA_BACKUP_CODE_USED,
    MFA_BACKUP_CODES_REGENERATED,
    PASSKEY_REGISTRATION_STARTED,
    PASSKEY_REGISTERED,
    PASSKEY_AUTHENTICATION_STARTED,
    PASSKEY_AUTHENTICATED,
    PASSKEY_FAILED,
    PASSKEY_DISABLED,
    OAUTH_AUTHORIZATION_CODE_ISSUED,
    OAUTH_TOKEN_ISSUED,
    OAUTH_CONSENT_GRANTED,
    OAUTH_CLIENT_CREATED,
    OAUTH_CLIENT_UPDATED,
    ADMIN_ACTION,
    ACCOUNT_DELETION_REQUESTED,
    ACCOUNT_ANONYMIZED,
    DATA_EXPORT_REQUESTED
}
