package io.github.brenomega.authkit.domain.user.entity;

import io.github.brenomega.authkit.domain.user.enums.Role;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Core identity entity representing a registered user (DT 3.1.2).
 *
 * <p>This entity is intentionally kept agnostic of the Spring Security
 * framework. Security concerns (e.g.&nbsp;{@code UserDetails}) are handled by
 * a separate wrapper class in the infrastructure layer.</p>
 *
 * <p>The primary key is a UUID generated by the JPA provider, stored as a
 * {@code String} to guarantee non-sequential, globally unique identifiers
 * across distributed instances (DT 3.1.21).</p>
 *
 * <p><strong>PII safety:</strong> {@link #toString()} is overridden to mask
 * the email and completely exclude the password hash, preventing accidental
 * leakage in log output (DT 3.4.9).</p>
 *
 * @see io.github.brenomega.authkit.infrastructure.security.SecurityUser
 */
@Entity
@Table(name = "users")
@FilterDef(name = "tenantFilter", parameters = {@ParamDef(name = "tenantId", type = String.class)})
@Filter(name = "tenantFilter", condition = "tenant_id = :tenantId")
public class User {

    /**
     * Universally unique identifier — primary key (DT 3.1.21).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", length = 36, nullable = false, updatable = false)
    private String id;

    /**
     * User's email address, used as the login credential.
     */
    @NotBlank
    @Email
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * Hashed password (Argon2id). The plaintext value is never stored (DT 3.2.1).
     */
    @NotBlank
    @Column(name = "password", nullable = false)
    private String password;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 50)
    private Role role = Role.USER;

    /**
     * Multi-tenancy isolation identifier.
     */
    @Column(name = "tenant_id", length = 36, nullable = false, unique = true, updatable = false)
    private String tenantId;

    /** Optional display name. */
    @Column(name = "name", length = 100)
    private String name;

    /** Optional contact phone number. */
    @Column(name = "phone", length = 20)
    private String phone;

    /** Proof of acceptance of Terms of Use. */
    @Column(name = "terms_accepted", nullable = false)
    private boolean termsAccepted;

    /** Proof of acceptance of Privacy Policy. */
    @Column(name = "privacy_policy_accepted", nullable = false)
    private boolean privacyPolicyAccepted;

    /** Restricts full write capabilities until verified. */
    @Column(name = "email_confirmed", nullable = false)
    private boolean emailConfirmed;

    /** Generated token sent asymptotically via RabbitMQ / Resend. */
    @Column(name = "email_confirmation_token", length = 100)
    private String emailConfirmationToken;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * JPA-required no-arg constructor.
     */
    protected User() {
    }

    /**
     * Creates a new user mapping explicitly from registration coordinates.
     * Generates a universally unique tenant identifier tied to the user upon creation.
     */
    public User(String email, String password, String name, String phone,
                boolean termsAccepted, boolean privacyPolicyAccepted,
                String emailConfirmationToken) {
        this.email = email;
        this.password = password;
        this.name = name;
        this.phone = phone;
        this.termsAccepted = termsAccepted;
        this.privacyPolicyAccepted = privacyPolicyAccepted;
        this.emailConfirmationToken = emailConfirmationToken;

        this.role = Role.USER;
        this.tenantId = java.util.UUID.randomUUID().toString();
        this.emailConfirmed = false;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    /** @return the UUID primary key */
    public String getId() {
        return id;
    }

    /** @return the user's email address */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the new email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return the hashed password */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the new hashed password (never plaintext)
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /** @return the user's role */
    public Role getRole() {
        return role;
    }

    /**
     * @param role the new role
     */
    public void setRole(Role role) {
        this.role = role;
    }

    public String getTenantId() { return tenantId; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }
    public boolean isTermsAccepted() { return termsAccepted; }
    public boolean isPrivacyPolicyAccepted() { return privacyPolicyAccepted; }
    public boolean isEmailConfirmed() { return emailConfirmed; }
    public void setEmailConfirmed(boolean emailConfirmed) { this.emailConfirmed = emailConfirmed; }
    public String getEmailConfirmationToken() { return emailConfirmationToken; }
    public void setEmailConfirmationToken(String emailConfirmationToken) { this.emailConfirmationToken = emailConfirmationToken; }

    // -------------------------------------------------------------------------
    // PII-safe toString (DT 3.4.9)
    // -------------------------------------------------------------------------

    /**
     * Returns a log-safe string that masks the email and excludes the password.
     *
     * <p>Example output: {@code User{id='abc-123', email='u***@example.com', role=USER}}</p>
     *
     * @return a sanitized string representation
     */
    @Override
    public String toString() {
        return "User{id='" + id + "', email='" + maskEmail(email) + "', role=" + role + '}';
    }

    /**
     * Masks an email address, keeping only the first character of the local
     * part and the full domain.
     *
     * @param email the original email
     * @return the masked email, e.g. {@code u***@example.com}
     */
    private static String maskEmail(String email) {
        if (email == null || !email.contains("@")) {
            return "[REDACTED]";
        }
        int atIndex = email.indexOf('@');
        return email.charAt(0) + "***" + email.substring(atIndex);
    }
}
